/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0B4a8snT1uC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function InputComponent() {
  return (
    (<div className="flex justify-center items-center h-screen bg-gray-100">
      <div className="bg-white p-10 rounded-lg shadow-lg">
        <h1 className="text-2xl font-bold text-center mb-4">Please enter your Voting code</h1>
        <div className="flex justify-center mb-8">
          <Input
            className="border-2 border-blue-500 p-2 text-center w-64"
            placeholder="Enter code here"
            type="text" />
        </div>
        <div className="flex justify-center">
          <div className="grid grid-cols-6 gap-2">
            <Input className="border-2 border-blue-500 w-10 p-2 text-center" />
            <Input className="border-2 border-blue-500 w-10 p-2 text-center" />
            <Input className="border-2 border-blue-500 w-10 p-2 text-center" />
            <Input className="border-2 border-blue-500 w-10 p-2 text-center" />
            <Input className="border-2 border-blue-500 w-10 p-2 text-center" />
            <Input className="border-2 border-blue-500 w-10 p-2 text-center" />
          </div>
        </div>
        <div className="flex justify-center mt-8">
          <Button className="bg-blue-500 text-white px-4 py-2 rounded">Submit</Button>
        </div>
      </div>
    </div>)
  );
}
